PS F:\Project\WebSite\InvoiceFlow> npm run electron:dev
> invoiceflow@0.1.0 electron:dev
> concurrently "npm run dev" "wait-on http://localhost:9002 && electron ."

(node:15712) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[0]
[0] > invoiceflow@0.1.0 dev
[0] > next dev --turbopack -p 9002
[0]
[0]    ▲ Next.js 15.2.3 (Turbopack)
[0]    - Local:        http://localhost:9002
[0]    - Network:      http://192.168.1.3:9002
[0]
[0]  ✓ Starting...
[0] Slow filesystem detected. If F:\Project\WebSite\InvoiceFlow\.next is a network drive, consider moving it to a local folder. If you have an antivirus enabled, consider excluding your project directory.
[0]  ✓ Ready in 1276ms
[0]  ○ Compiling / ...
[0]  ✓ Compiled / in 1909ms
[0]  HEAD / 200 in 1466ms
[0]  HEAD / 200 in 2219ms
[0]  HEAD / 200 in 1722ms
[0]  HEAD / 200 in 2385ms
[0]  HEAD / 200 in 1276ms
[0]  HEAD / 200 in 521ms
[0]  HEAD / 200 in 2027ms
[0]  HEAD / 200 in 2428ms
[0]  HEAD / 200 in 2428ms
[0]  HEAD / 200 in 2428ms
[0]  HEAD / 200 in 775ms
[0]  HEAD / 200 in 2432ms
[0]  HEAD / 200 in 1028ms
[1]
[1] App threw an error during load
[1] Error: Cannot find module '../src/lib/database'
[1] Require stack:
[1] - F:\Project\WebSite\InvoiceFlow\electron\main.js
[1]     at Module._resolveFilename (node:internal/modules/cjs/loader:1408:15)
[1]     at s._resolveFilename (node:electron/js2c/browser_init:2:129305)
[1]     at defaultResolveImpl (node:internal/modules/cjs/loader:1064:19)
[1]     at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1069:22)
[1]     at Module._load (node:internal/modules/cjs/loader:1218:37)
[1]     at c._load (node:electron/js2c/node_init:2:17950)
[1]     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
[1]     at wrapModuleLoad (node:internal/modules/cjs/loader:242:24)
[1]     at Module.require (node:internal/modules/cjs/loader:1494:12)
[1]     at require (node:internal/modules/helpers:135:16)